use anyhow::{Context, Result, anyhow};
use ignore::WalkBuilder;
use once_cell::sync::Lazy;
use rayon::prelude::*;
use regex::Regex;
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Component, Path, PathBuf};
use std::process::ExitCode;
use unicode_normalization::UnicodeNormalization;

// §AR-bindings.1: `grund-core` is the shared implementation crate used by the
// published `grund` CLI and, next, the optional LSP server. The category files
// are still included flat to keep this first package split behavior-preserving.
include!("grammar.rs");
include!("id_format.rs");
include!("id_grammar_rules.rs");
include!("shorthand.rs");
include!("model.rs");
include!("config_discovery.rs");
include!("config.rs");
include!("config_cmd.rs");
include!("comment_line.rs");
include!("inline_note_layout.rs");
include!("scanner_walk.rs");
include!("scanner_walk_errors.rs");
include!("scanner.rs");
include!("checker.rs");
include!("checker_sections.rs");
include!("checker_references.rs");
include!("checker_cmd.rs");
include!("workspace_scope.rs");
include!("workspace_members.rs");
include!("workspace_context.rs");
include!("workspace_expand.rs");
include!("output.rs");
include!("show.rs");
include!("show_render.rs");
include!("show_body.rs");
include!("fmt.rs");
include!("fmt_cmd.rs");
include!("fmt_links.rs");
include!("id.rs");
include!("refs.rs");
include!("cover.rs");
include!("list.rs");
include!("completions.rs");
include!("integrations.rs");
include!("init_templates.rs");
include!("init_entrypoints.rs");
include!("init_plan.rs");
include!("init_block.rs");
include!("init_notes.rs");
include!("init_target.rs");
include!("init.rs");
include!("api.rs");
include!("on_type.rs");
include!("lsp_hover.rs");
include!("compat_cli.rs");
// Tests, one module per category (§AR-core-module-layout.1). `tests_support`
// holds the fixtures they share and must come first.
include!("tests_support.rs");
include!("tests_config_discovery.rs");
include!("tests_config_scan.rs");
include!("tests_id_grammar.rs");
include!("tests_check_full.rs");
include!("tests_check_full_scope.rs");
include!("tests_nothing_recognized.rs");
include!("tests_duplicate_sections.rs");
include!("tests_section_body_scope.rs");
include!("tests_grounding_style.rs");
include!("tests_inline_note_layout.rs");
include!("tests_inline_note_layout_check.rs");
include!("tests_scanner.rs");
include!("tests_scanner_walk.rs");
include!("tests_scanner_walk_errors.rs");
include!("tests_shorthand.rs");
include!("tests_shorthand_rewrite.rs");
include!("tests_shorthand_surfaces.rs");
include!("tests_shorthand_numeric_run.rs");
include!("tests_citation_directions.rs");
include!("tests_managed_block_drift.rs");
include!("tests_workspace.rs");
include!("tests_workspace_message_paths.rs");
include!("tests_workspace_nested.rs");
include!("tests_workspace_claims.rs");
include!("tests_workspace_claim_answers.rs");
include!("tests_alias_hints.rs");
include!("tests_workspace_members.rs");
include!("tests_cover_workspace.rs");
include!("tests_init_agents.rs");
include!("tests_init_target.rs");
include!("tests_integrations.rs");
include!("tests_integrations_config.rs");
include!("tests_resolver.rs");
include!("tests_clickable_citations.rs");
include!("tests_api.rs");
include!("tests_lsp_hover.rs");
